- name: my play to project 2
  hosts: liki
  become: true
  tasks:
    - name: uupdate repos
      command: apt update
    - name: install docker
      package: name=docker.io state=present
    - name: docker con
      command: docker run -d -p 8888:8082 likith2468/health:5
